- hosts: HTTP
  tasks:
  - package:
      name: "httpd"
      state: present

  - copy:
      dest: "/var/www/html/index.html"
      content: "hello bro this is my page"

  - replace:
      path: "/etc/httpd/conf/httpd.conf"
      regexp: "AllowOverride None"
      replace: "AllowOverride AuthConfig"

  - copy:
      dest: "/var/www/html/.htaccess"
      src: "/var/www/html/.htaccess"

  - package:
      name: "python36"

  - name: install python library
    pip:
      name: passlib

  - htpasswd:
      path: "/etc/www.passwd"
      name: "manali"
      password: "manali"
  
